version: '3.6'

services:

  postgres-demo:
    image: postgres
    container_name: postgres-demo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=app
    ports:
      - 5432:5432